version: '3.7'
services:
  getdiscordusers:
    build: .
    image: getdiscordusers:latest
    environment:
      TOKEN: ODI1Njk3NjI3OTMyMTk2ODg0.YGBs1w.Y0NRfuVowGGNDZes_BKcixRZ8lY
      CHANNEL: general
